"""
Review Agent — code review for the Gene Story project.

This agent reads a source file, reviews it using Claude, and produces
a plain-English report that a non-developer (e.g. a biologist) can
understand. It checks:
  - What the code does (explained simply)
  - Whether it is clearly documented
  - Whether functions/variables have sensible names
  - Whether error handling is present where needed
  - Any security or data integrity concerns

Usage (via Claude Code slash command):
  /review api/routes/genes.py
  /review parser/gtf_parser.py

Or directly:
  python agents/review_agent.py api/routes/genes.py

The report is saved to REVIEW_REPORT.md and also printed to the terminal.
"""

import os
import sys
from datetime import datetime
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv()

REVIEW_PROMPT = """\
You are reviewing code for the "Gene Story" project — a web application that \
reads genomic annotation data and generates AI-written gene stories for a \
book-like interface.

Your audience for this review is a mixed team: bioinformaticians who understand \
genomics but not software engineering deeply, and the occasional developer. \
Write your review so that a biologist can understand what the code does and \
whether it looks correct, even if they don't know the programming language well.

File being reviewed: {filename}

```
{code}
```

Please provide a structured review covering:

1. PLAIN ENGLISH SUMMARY
   What does this file do? Explain it as you would to a biologist with no \
   coding background.

2. DOCUMENTATION CHECK
   Are functions and modules explained clearly? Is there enough context for \
   a newcomer to understand why each function exists?

3. CODE QUALITY
   Are there any confusing patterns, overly complex logic, or naming that \
   could be improved? Keep this practical and brief.

4. ERROR HANDLING
   Are potential failures handled gracefully? (e.g. missing files, \
   database errors, API failures)

5. CONCERNS OR SUGGESTIONS
   Any security issues, data integrity risks, or important improvements \
   to consider?

6. OVERALL ASSESSMENT
   One paragraph summarising the health of this file and what to prioritise \
   if making changes.

Be honest but constructive. If the code is well written, say so clearly.
"""


def review_file(file_path: str) -> str:
    """Read a file and return a Claude-generated review."""
    path = Path(file_path)

    if not path.exists():
        return f"Error: File not found: {file_path}"

    code = path.read_text(encoding="utf-8")

    if not code.strip():
        return f"Error: File is empty: {file_path}"

    print(f"Reviewing: {path}")
    print("Connecting to Claude API…")

    client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        messages=[
            {
                "role": "user",
                "content": REVIEW_PROMPT.format(
                    filename=path.name,
                    code=code,
                ),
            }
        ],
    )

    return message.content[0].text


def save_report(review_text: str, file_path: str) -> None:
    """Write the review report to REVIEW_REPORT.md."""
    report_path = Path("REVIEW_REPORT.md")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = f"""# Code Review Report

**File reviewed:** `{file_path}`
**Date:** {timestamp}
**Reviewer:** Claude Sonnet (automated)

---

{review_text}

---
*Generated by the Gene Story Review Agent — run with `/review <file>`*
"""

    report_path.write_text(report, encoding="utf-8")
    print(f"\nReport saved to: {report_path.absolute()}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python agents/review_agent.py <file_path>")
        print("Example: python agents/review_agent.py api/routes/genes.py")
        sys.exit(1)

    file_path = sys.argv[1]
    review    = review_file(file_path)

    print("\n" + "═" * 60)
    print(review)
    print("═" * 60)

    save_report(review, file_path)


if __name__ == "__main__":
    main()
